# Creates the isle-registry network and setups a local Docker image registry for testing purposes.
---
version: "3.8"

# Common to all services
x-common: &common
  restart: "no"

volumes:
  registry-data: {}

networks:
  default:
    name: ${NETWORK_NAME}

services:
  registry:
    <<: *common
    image: registry:${REGISTRY_TAG}
    container_name: ${REGISTRY_NAME}
    environment:
      REGISTRY_HTTP_ADDR: "0.0.0.0:443"
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      REGISTRY_HTTP_TLS_CERTIFICATE: "/usr/local/share/ca-certificates/cert.pem"
      REGISTRY_HTTP_TLS_KEY: "/usr/local/share/ca-certificates/privkey.pem"
    ports:
      - "${REGISTRY_PORT}:443"
    volumes:
      - registry-data:/var/lib/registry
      - ./certs/cert.pem:/usr/local/share/ca-certificates/cert.pem:ro
      - ./certs/privkey.pem:/usr/local/share/ca-certificates/privkey.pem:ro
      - ./certs/rootCA.pem:/usr/local/share/ca-certificates/rootCA.pem:ro
    networks:
      default:
        aliases: [ "islandora.io" ]
  ui:
    image: joxit/docker-registry-ui:${REGISTRY_UI_TAG}
    container_name: ${REGISTRY_NAME}-ui
    ports:
      - "${REGISTRY_UI_PORT}:80"
    environment:
      - REGISTRY_TITLE=${REGISTRY_NAME}
      - PULL_URL=islandora.io:${REGISTRY_PORT}
      - DELETE_IMAGES=true
      - SHOW_CATALOG_NB_TAGS=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=https://islandora.io
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
